/**
 * PRODUCT CATALOG DATA
 * ====================
 * To add a new product: copy any object below and update the fields.
 * To edit a product: change "name" and "description" (both are PLACEHOLDER text).
 * Image paths follow the pattern: images/{number}.jpg
 */

const PRODUCTS = [
  { id: 1,   image: "images/1.jpg",   name: "Moorish Star Arch Panel", description: "A white, arched wall niche featuring an intricate, illuminated geometric Moorish star pattern cutout." },
  { id: 2,   image: "images/2.jpg",   name: "Sculpted Flora Archway", description: "Two soft-lit arched wall niches featuring a 3D sculpted flowing leaf design and vertical fluting." },
  { id: 3,   image: "images/3.jpg",   name: "Textured Stone Salon Arches", description: "Three illuminated arched wall niches with a rough, stone-like texture positioned behind salon chairs." },
  { id: 4,   image: "images/4.jpg",   name: "Jagged Stone & Marble Edge", description: "A decorative wall featuring a rugged, illuminated stone-like texture overlapping a smooth white marble surface." },
  { id: 5,   image: "images/5.jpg",   name: "Illuminated Vine Relief", description: "A tall, backlit vertical wall panel displaying a 3D sculpted relief of a winding leafy vine." },
  { id: 6,   image: "images/6.jpg",   name: "Curved Wood Console", description: "A fluid, ribbon-like wooden console table paired with a round wood-framed mirror against a textured stone wall." },
  { id: 7,   image: "images/7.jpg",   name: "Golden Edge Lily Relief", description: "A rectangular wall panel showcasing a 3D relief of elegant white lily-like flowers highlighted with gold edges." },
  { id: 8,   image: "images/8.jpg",   name: "Abstract Wave Relief", description: "An illuminated hallway wall panel displaying a large, flowing, abstract 3D relief resembling stylized waves or floral petals." },
  { id: 9,   image: "images/9.jpg",   name: "Impasto Swirl Roses", description: "A textured white canvas art piece featuring large swirling rose patterns and a heavy gold leaf base section." },
  { id: 10,  image: "images/10.jpg",  name: "Sculpted Floral Bloom Panel", description: "A large backlit vertical wall panel featuring a beautifully sculpted 3D relief of a blooming flower and buds." },
  { id: 11,  image: "images/11.jpg",  name: "Close-up Impasto Roses", description: "A detailed view of a textured wall art piece showing swirling impasto rose patterns above a rugged gold leaf section." },
  { id: 12,  image: "images/12.jpg",  name: "Art Deco Fan Pattern Wall", description: "A balcony accent wall featuring an intricate, illuminated 3D geometric pattern of overlapping fan shapes with gold accents." },
  { id: 13,  image: "images/13.jpg",  name: "Backlit Textured Stone Panels", description: "An accent wall constructed from illuminated rectangular stone panels with a highly textured, rugged surface in warm beige tones." },
  { id: 14,  image: "images/14.jpg",  name: "Faceted Geometric Mirror Wall", description: "A 3D wall installation featuring faceted triangular panels mixed with mirrored sections for a geometric, modern look." },
  { id: 15,  image: "images/15.jpg",  name: "Triptych Leaf Relief", description: "Three framed rectangular wall panels displaying a delicate, flowing 3D relief of layered leaves in neutral and gold tones." },
  { id: 16,  image: "images/16.jpg",  name: "Pink and Cream Rose Canvas", description: "A heavily textured rectangular canvas featuring swirling impasto rose patterns in soft pink, cream, and gold." },
  { id: 17,  image: "images/17.jpg",  name: "Black Geometric Wall Panels", description: "A collage showcasing a set of black 3D wall decor panels with varying geometric, wavy, and starry patterns." },
  { id: 18,  image: "images/18.jpg",  name: "Curved Lines & Marble Shapes", description: "A modern interior wall displaying an abstract 3D relief of continuous curved white lines mixed with dark green marble-like organic shapes." },
  { id: 19,  image: "images/19.jpg",  name: "Monstera Leaf Canvas", description: "A textured canvas painting depicting green Monstera leaves and pale pampas grass, mounted on a dark marble wall." },
  { id: 20,  image: "images/20.jpg",  name: "Horizontal Impasto Flowers", description: "A wide canvas art piece featuring thickly textured, swirling white flowers with jewel-like centers above a gold leaf bottom border." },
  { id: 21,  image: "images/21.jpg",  name: "Textured Pastel Rose Impasto", description: "A narrow vertical canvas featuring heavily textured, sculpted roses in soft pink, cream, and gold tones." },
  { id: 22,  image: "images/22.jpg",  name: "Tropical Leaf Impasto Canvas", description: "A vertical textured artwork depicting stylized green monstera and palm leaves on a beige background above a console table." },
  { id: 23,  image: "images/23.jpg",  name: "Monstera Leaf Relief Close-Up", description: "A close-up view of thick impasto painting showing raised, sculpted green monstera leaves and beige fronds." },
  { id: 24,  image: "images/24.jpg",  name: "Large 3D Botanical Wall Mural", description: "An oversized 3D embossed wall design featuring giant cream and green tropical leaves and blossoms behind a living room sofa." },
  { id: 25,  image: "images/25.jpg",  name: "Carved Plaster Fern Wall Art", description: "A monochromatic, deeply carved white wall mural showing intricate, curving fern and vine motifs in a minimalist interior." },
  { id: 26,  image: "images/26.jpg",  name: "Giant 3D Floral Spiral", description: "A massive, back-lit 3D wall feature depicting a stylized lotus or dahlia flower with radiating, sculptural petals above a couch." },
  { id: 27,  image: "images/27.jpg",  name: "Illuminated Zen Mountain Relief", description: "A circular bas-relief wall art with backlighting, featuring a tranquil landscape of mountains, a bonsai tree, and a pagoda." },
  { id: 28,  image: "images/28.jpg",  name: "Metallic Pastel Leaves Pattern", description: "A dense, overlapping 3D composition of stylized leaves in pastel pink, mint, and blue with gleaming gold metallic outlines." },
  { id: 29,  image: "images/29.jpg",  name: "Oversized Tropical Bedroom Mural", description: "A large-scale mural showing lush, oversized green monstera and palm leaves behind a modern upholstered bed." },
  { id: 30,  image: "images/30.jpg",  name: "Abstract 3D Fish School Sculptures", description: "A sweeping wall installation composed of numerous 3D diamond or fish-shaped pieces in white and teal on a concrete wall." },
  { id: 31,  image: "images/31.jpg",  name: "3D White and Gold Leaf Relief", description: "A decorative living room wall feature with sweeping, sculpted white leaves and a metallic gold accent branch." },
  { id: 32,  image: "images/32.jpg",  name: "Twin Stone Texture Wall Panels", description: "Two tall, rectangular wall panels featuring rugged, natural stone-like textures flanking a bed in a minimalist room." },
  { id: 33,  image: "images/33.jpg",  name: "Sculpted Floral Butterfly", description: "A large, pure white 3D butterfly wall sculpture whose wings are densely adorned with carved blossoms and foliage." },
  { id: 34,  image: "images/34.jpg",  name: "Impasto Snowy Mountain Diptych", description: "A two-panel artwork showing extreme, thick white impasto ridges resembling snowy peaks, with tiny painted hikers." },
  { id: 35,  image: "images/35.jpg",  name: "Large Impasto Snow Landscape", description: "A living room setting displaying a large diptych of thick white impasto ridges forming snowy mountains with miniature red figures." },
  { id: 36,  image: "images/36.jpg",  name: "Vintage Tropical Palm Wallpaper", description: "A soft, muted mural illustrating a dense tropical jungle filled with various stylized palm trees and botanical foliage." },
  { id: 37,  image: "images/37.jpg",  name: "Textured Vase Painting", description: "A large square artwork with a grid-like impasto background depicting a realistic 3D-effect grey ceramic vase." },
  { id: 38,  image: "images/38.jpg",  name: "Sweeping Green Abstract Impasto", description: "A massive horizontal canvas featuring thick, sweeping layers of textured paint in gradient shades of teal, green, and cream." },
  { id: 39,  image: "images/39.jpg",  name: "Giant Plaster Floral Relief", description: "A large-scale wall installation of sculpted, oversized white blossoms and light green leaves with intricate bas-relief details." },
  { id: 40,  image: "images/40.jpg",  name: "Textured Emirati Leader Portrait", description: "A heavily textured, mosaic-like portrait of an Emirati figure with gold leaf accents, displayed in a modern corridor." },
  { id: 41,  image: "images/41.jpg",  name: "Emirati Mosaic Portrait", description: "A framed mosaic portrait of two Arab men in traditional clothing, displayed in an elegant living room." },
  { id: 42,  image: "images/42.jpg",  name: "Dreamy 3D Floral Moon Relief", description: "A 3D white relief artwork showing blooming trees, flowers, and a large textured moon in a dreamlike setting." },
  { id: 43,  image: "images/43.jpg",  name: "Sculpted Peacock & Magnolia Wall Art", description: "A detailed 3D relief of a peacock with blue and white plumage perched among white magnolia flowers on a white background." },
  { id: 44,  image: "images/44.jpg",  name: "Abstract White & Gold Floral Canvas", description: "A textured abstract floral painting with large white petals and gold leaf accents hanging above a dining table." },
  { id: 45,  image: "images/45.jpg",  name: "Oversized 3D Floral Wall Mural", description: "A large 3D wall mural of oversized white flowers with greenish leaves set against a textured seafoam green wall behind a sitting area." },
  { id: 46,  image: "images/46.jpg",  name: "Tropical Leaf 3D Relief Wall Art", description: "A 3D wall art installation of large overlapping green and cream tropical leaves behind a modern white sectional sofa." },
  { id: 47,  image: "images/47.jpg",  name: "Lush Botanical 3D Wall Sculptures", description: "A large textured wall display featuring oversized tropical leaves and delicate white flowers positioned behind a modern cream-colored sofa." },
  { id: 48,  image: "images/48.jpg",  name: "Textured White Petals with Gold Accents", description: "A heavily textured abstract painting depicting a large white flower with prominent gold leaf accents along the edges and center." },
  { id: 49,  image: "images/49.jpg",  name: "Golden Vein Floral Wall Canvas", description: "A large framed abstract floral canvas with thick impasto white petals and golden accents, displayed in a bright hallway." },
  { id: 50,  image: "images/50.jpg",  name: "Organic Pebble Mirror Wall Feature", description: "A wall design featuring four irregular pebble-shaped mirrors mounted on white wainscoting flanked by vertical wooden slat panels with warm backlighting." },
  { id: 51,  image: "images/51.jpg",  name: "Stepped Vertical Mirror Panel Design", description: "A white slatted wall featuring elongated pill-shaped vertical mirrors in a stepped pattern, flanked by brown panels with modern sconces." },
  { id: 52,  image: "images/52.jpg",  name: "Flowing 3D Wave Wall Panel", description: "A decorative white wall feature with flowing 3D wave-like relief patterns positioned behind a long minimalist console table." },
  { id: 53,  image: "images/53.jpg",  name: "Elegant Calla Lily 3D Mural", description: "A large, elegant 3D relief mural of calla lilies set within a warmly lit rectangular alcove in a living space." },
  { id: 54,  image: "images/54.jpg",  name: "Modern Arched Grid Staircase Wall", description: "A tall staircase wall featuring a grid of white textured panels with arched motifs, interspersed with modern dual-beam wall sconces." },
  { id: 55,  image: "images/55.jpg",  name: "Backlit Star-Grid Wall Panel", description: "A decorative interior wall panel with a grid of rounded rectangular tiles and recessed star-shaped intersections emitting a warm backlight." },
  { id: 56,  image: "images/56.jpg",  name: "Cascading Luminous Petal Chandelier", description: "A massive cascading lighting feature made of glowing white petal-like shapes falling against a textured wall between tall wooden slats." },
  { id: 57,  image: "images/57.jpg",  name: "Geometric Multi-Texture 3D Wall Art", description: "A decorative backlit 3D panel with multiple overlapping rounded shapes featuring various geometric grids and organic wave textures." },
  { id: 58,  image: "images/58.jpg",  name: "3D Gold Sunflowers on Black Canvas", description: "A textured black canvas painting with striking 3D gold sunflowers and leaves hung in a contemporary dining area with dark wood paneling." },
  { id: 59,  image: "images/59.jpg",  name: "Flowing Botanical 3D Relief Sculpture", description: "A framed 3D relief wall sculpture showing graceful, flowing floral and botanical stems above a modern seating arrangement." },
  { id: 60,  image: "images/60.jpg",  name: "Vertical Organic Wave Wall Panel", description: "A tall, textured white 3D wall panel displaying organic, fluid vertical waves and ridges, set between two white walls near a window." },
  { id: 61,  image: "images/61.jpg",  name: "Vertical Wood Slat Panel", description: "A sleek decorative wall panel featuring repetitive vertical wooden slats with a natural brown finish." },
  { id: 62,  image: "images/62.jpg",  name: "Intricate White Arches Relief", description: "A large white textured wall feature composed of various intricately carved arches, windows, and traditional patterned reliefs stacked together." },
  { id: 63,  image: "images/63.jpg",  name: "Gold & Black Sunflower Canvas", description: "A vertical rectangular canvas featuring thick, textured golden sunflowers and lilies standing against a stark black background." },
  { id: 64,  image: "images/64.jpg",  name: "Flowing Organic Botanical Carving", description: "A tall white panel showing deeply carved, flowing organic lines intertwining with elegant floral and feather-like shapes, enhanced by side lighting." },
  { id: 65,  image: "images/65.jpg",  name: "Wild Meadow Floral Relief", description: "A vertical white sculpted relief depicting tall, slender wild grass and meadow flowers against a softly lit background." },
  { id: 66,  image: "images/66.jpg",  name: "Curved Forest Staircase Bas-Relief", description: "A curved staircase wall adorned with a warm, sandy-colored bas-relief showing intricate forest elements like leaves, trees, and small animals." },
  { id: 67,  image: "images/67.jpg",  name: "White Mangrove Jungle Sculpture", description: "A massive white wall sculpture displaying a deeply textured jungle scene with prominent mangrove roots, trees, and monkeys." },
  { id: 68,  image: "images/68.jpg",  name: "Stylized Weeping Tree Relief", description: "A tall, elegant white wall carving showcasing a stylized tree with clustered foliage and vertical descending lines." },
  { id: 69,  image: "images/69.jpg",  name: "Tropical Leaves and Berries Mural", description: "A textured, beige-colored bas-relief wall section filled with densely carved tropical leaves, branches, and clustered berries." },
  { id: 70,  image: "images/70.jpg",  name: "Galloping Wild Horses 3D Art", description: "A dynamic white 3D wall sculpture featuring a herd of stylized wild horses galloping forward with flowing manes." },
  { id: 71,  image: "images/71.jpg",  name: "Backlit Layered Leaves Feature", description: "A vertical wall feature composed of large, overlapping white sculpted leaves with warm backlighting glowing from behind the edges." },
  { id: 72,  image: "images/72.jpg",  name: "Abstract Gold & White Floral Impasto", description: "An abstract canvas art piece with heavy white impasto texture forming large floral shapes highlighted with rich gold leaf accents." },
  { id: 73,  image: "images/73.jpg",  name: "Textured White & Gold Petals Artwork", description: "A heavily textured horizontal canvas displaying large, abstract white floral petals with striking gold detailing in the center." },
  { id: 74,  image: "images/74.jpg",  name: "White 3D Sprawling Blossom Branch", description: "A large rectangular white wall sculpture displaying a sprawling, elegant branch filled with delicate 3D blossoms and leaves." },
  { id: 75,  image: "images/75.jpg",  name: "Illuminated Wavy Beige Wall Panel", description: "A contemporary living room wall featuring thick, undulating beige 3D waves with integrated warm backlighting along the sweeping curves." },
  { id: 76,  image: "images/76.jpg",  name: "Crane and Golden Sun Relief", description: "A textured wall relief showing a large white crane standing near a gnarly pine tree branch reaching towards a bright golden circular sun." },
  { id: 77,  image: "images/77.jpg",  name: "Cranes & Floral Jagged Edge Carving", description: "A white wall carving featuring two cranes in water and a cluster of flowers, bordered by a dramatic jagged edge with warm backlighting." },
  { id: 78,  image: "images/78.jpg",  name: "Backlit Tree with Falling Leaves", description: "A stunning wall installation depicting a winding tree trunk and branches with large sculpted leaves appearing to fall, illuminated by backlighting." },
  { id: 79,  image: "images/79.jpg",  name: "Textured White Roses with Gold Base", description: "A wide horizontal canvas featuring heavily textured, stylized white roses above a thick, abstract gold-painted lower section." },
  { id: 80,  image: "images/80.jpg",  name: "Geometric Patchwork Canvas", description: "A square artwork divided into distinct puzzle-like sections of different colors and textures, separated by striking gold leaf veins." },
  { id: 81,  image: "images/81.jpg",  name: "Abstract Textural Wall Art", description: "A textured multi-colored geometric block wall artwork above a sofa." },
  { id: 82,  image: "images/82.jpg",  name: "Twisted Gold Wall Sculpture", description: "A folded, metallic gold sculptural accent piece mounted on a modern wooden wall." },
  { id: 83,  image: "images/83.jpg",  name: "Relief Monstera Leaves Wall Mural", description: "A green large-scale relief sculpture of overlapping monstera leaves on a living room wall." },
  { id: 84,  image: "images/84.jpg",  name: "Relief Tree & Pastoral Wall Mural", description: "A sprawling, detailed relief sculpture featuring a large flowering tree, birds, and animals on a light gray wall." },
  { id: 85,  image: "images/85.jpg",  name: "Relief Cranes & Tropical Foliage", description: "An intricate relief sculpture showcasing cranes standing among tropical foliage and hibiscus flowers." },
  { id: 86,  image: "images/86.jpg",  name: "Relief Floral & Cranes Wall Art", description: "A white relief wall piece featuring a floral arrangement and two cranes standing in water." },
  { id: 87,  image: "images/87.jpg",  name: "Relief Tropical Landscape", description: "A multi-layered relief carving of birds flying over a calm landscape with stylized banana and lotus leaves." },
  { id: 88,  image: "images/88.jpg",  name: "Peacock Wooden Relief Carving", description: "A detailed wooden relief carving of two peacocks surrounded by decorative swirling foliage." },
  { id: 89,  image: "images/89.jpg",  name: "Tropical Birds & Plants Relief", description: "A detailed relief sculpture featuring birds flying over a lush landscape of large stylized leaves." },
  { id: 90,  image: "images/90.jpg",  name: "Lotus Flower Bas-Relief Panel", description: "An elegant bas-relief wall sculpture depicting blooming lotus flowers, lily pads, and stylized clouds." },
  { id: 91,  image: "images/91.jpg",  name: "Heron & Banana Leaves Relief", description: "A delicate white bas-relief featuring a heron and large banana leaves placed behind a brass fixture." },
  { id: 92,  image: "images/92.jpg",  name: "Illuminated Tropical Flora Panel", description: "A vertical, backlit white relief panel bursting with dense tropical plants and flowers." },
  { id: 93,  image: "images/93.jpg",  name: "Lotus Flowers & Clouds Relief", description: "An elegant bas-relief wall sculpture depicting blooming lotus flowers, lily pads, and stylized clouds." },
  { id: 94,  image: "images/94.jpg",  name: "Glowing Banana Leaves Sculpture", description: "A modern living space featuring a glowing, textured wall sculpture of large overlapping banana leaves." },
  { id: 95,  image: "images/95.jpg",  name: "Dense Fern & Botanical Bas-Relief", description: "A deeply carved white bas-relief panel showcasing a dense thicket of ferns, broad leaves, and small flowers." },
  { id: 96,  image: "images/96.jpg",  name: "Classical Scenic Landscape Mural", description: "An opulent staircase landing decorated with a painted mural of a classical landscape with dancing figures." },
  { id: 97,  image: "images/97.jpg",  name: "Carved Wooden Arched Entrance Door", description: "An intricately carved, arched wooden double door set within a deeply ornamented stone entryway." },
  { id: 98,  image: "images/98.jpg",  name: "Modern Magenta Kitchen Cabinetry", description: "A moody, modern kitchen featuring dark magenta cabinets with gold hardware against a black backsplash." },
  { id: 99,  image: "images/99.jpg",  name: "Patterned Tile Kitchen Backsplash", description: "A warm wood kitchen accented with an array of vibrant, wildly patterned ceramic tiles on the backsplash." },
  { id: 100, image: "images/100.jpg", name: "Concentric Carved Wood Front Door", description: "A modern front door featuring elaborate, concentric circular patterns and ridged carvings in light wood." },
  { id: 101, image: "images/101.jpg", name: "Staircase Peacock Illuminated Cutouts", description: "A staircase featuring beautifully illuminated, arched wall cutouts showcasing peacocks and bright red floral motifs." },
  { id: 102, image: "images/102.jpg", name: "Backlit Blossom Tree Relief", description: "A stunning backlit relief wall carving of a large tree with soft, glowing blossoms above a sofa." },
  { id: 103, image: "images/103.jpg", name: "Vibrant Peacock Illuminated Relief", description: "A brilliantly colored relief artwork of a majestic peacock and delicate tree against a textured wall." },
  { id: 104, image: "images/104.jpg", name: "Deity & Peacock Terracotta Relief", description: "A warm terracotta relief panel featuring a central deity surrounded by elephants, peacocks, and floral motifs." },
  { id: 105, image: "images/105.jpg", name: "Classical Narrative Stone Relief", description: "A multi-tiered stone relief carving displaying processions of figures, horses, elephants, and chariots." },
  { id: 106, image: "images/106.jpg", name: "Banana Leaf & Soaring Birds Relief", description: "A white relief sculpture of lush banana leaves and soaring birds, adding texture to a calm space." },
  { id: 107, image: "images/107.jpg", name: "Flamingos & Tropical Outdoor Panel", description: "An outdoor courtyard featuring a large stone relief panel carved with elegant flamingos and stylized tropical plants." },
  { id: 108, image: "images/108.jpg", name: "Illuminated Cranes & Fronds Panel", description: "A softly lit bas-relief wall panel showcasing detailed carvings of cranes, hibiscus flowers, and palm fronds." },
  { id: 109, image: "images/109.jpg", name: "Teal Lotus Relief Triptych", description: "A three-piece teal wall installation showing carved lotus flowers and lily pads framed by fluted panels." },
  { id: 110, image: "images/110.jpg", name: "Carved Tropical Flora Wooden Panel", description: "A large, unfinished wooden relief panel intricately carved with detailed foliage, flowers, and flying birds." },
  { id: 111, image: "images/111.jpg", name: "Grand Cranes & Tropical Bas-Relief", description: "A wide, white bas-relief wall mural displaying multiple graceful cranes amidst dense tropical flowers and leaves." },
];
